	tilepal 0, GRAY, GREEN, GRAY, GRAY, RED, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, TEXT, TEXT, GRAY, GRAY, RED, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT, TEXT
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT, TEXT
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GREEN, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, TEXT, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GREEN, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, RED, RED
